apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    Version: 2.6.2
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp
        Version: 2.6.2
    spec:
      containers:
        - name: mycontainer
          image: mrudulagh/javaapp30sep:1
          ports:
            - containerPort: 8080
