apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 2
  selector:
    app: myjavaapp
    Version: 2.6.2
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp
        Version: 2.6.2
    spec:
      containers:
        - name: mycontainer
          image: maha4iac/myonlinebooking:2
          ports:
            - containerPort: 8080
